language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - "pip install coverage nose-cov flake8 python-coveralls"
  - "pip install -e ."

before_script: "flake8"

script:  "nosetests"

after_success:
    - coveralls
